version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery-worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info --concurrency=2 --queues=analysis,celery
    volumes:
      - .:/app
      - ./outputs:/app/outputs
      - ./data:/app/data
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_TYPE=sqlite
      - SQLITE_DB_PATH=/app/auth.db
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery-flower:
    build: .
    command: celery -A app.celery_app flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./outputs:/app/outputs
      - ./data:/app/data
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_TYPE=sqlite
      - SQLITE_DB_PATH=/app/auth.db
    depends_on:
      redis:
        condition: service_healthy
      celery-worker:
        condition: service_started
    restart: unless-stopped

volumes:
  redis_data:
